### ISSUE TITLE
友好交流

### ISSUE THREAD

**Issue by NickNYU** [RedisOptimal/redis-cluster-support-mget#1]
Hi
我从Redis3.2那个支持Mac M1芯片的Redis Issue过来的，顺带看了下其他文件，问下支持cluster模式下，多个key mget的Redis修改的逻辑是：

之前是基于slot的判定

修改为基于当前Redis server是否负责一个制定的slot，这样？

**Comment by RedisOptimal** [comment]
对，基本上就是你理解的内容。Redis Cluster的源码好多年都没改过了，难怪redis的作者离开了这个社区。
原来的逻辑是对于同一个slot进行mget操作，由于slot过多，通常来说每个slot也就只能分到2-3个key，就导致了mget执行效率过低。
我的改动是客户端，直接判断key位于同一台实例（Redis Instance）上，则对这个实例进行一次mget操作。
改动量并不是很大，且我们线上使用的效果还不错。

**Comment by NickNYU** [comment]
明白了，感谢
我去看下7.0有没有修复这个问题，7.0代码有些看不懂了，和4.x区别挺大。。。。
